### ISSUE TITLE
Error when importing

### ISSUE THREAD

**Issue by Rashidsalim** [VirtoCommerce/vc-module-shopify-import#2]
Hi,
Steps to reproduce:
 * Catalog > "Clothing" 
 * Select Import > Shopify import 
 * Object Type > Products
 * Get error "Import finished with errors"

I have tested all object types and the theme import seems to be the only one working. It successfully imported all themes in the shop.
Error: https://pastebin.com/HJMvfhCJ
Environment:
  * Running vc-platform  2.13.49 dev branch in Azure

Expected Behaviour:
  * Import finished successfully and object types appearing in catalog

Find Product export from shopify below
[example file.xlsx](https://github.com/VirtoCommerce/vc-module-shopify-import/files/3504780/example.file.xlsx)

**Comment by blazemachine** [comment]
Hi, @Rashidsalim. In researching your problem I followed by your steps and I am not meeting no one errors. For beginning, I created shop + private app in a shopify service. By next step was adding products for shop from file that you were attached. Further I'm using API-key + password of my shop and I'm trying to import products to my catalog in Virto Commerce platform. As result I see products that imported in catalog. I attached gif file with my actions and successful result.
![successful_import](https://user-images.githubusercontent.com/43133766/64019049-8a01c880-cb47-11e9-918a-318f1577caa3.gif)

**Comment by Rashidsalim** [comment]
Hi @blazemachine 
Apologize for the late response. Thank you for taking a look at my issue. I will do the same as you've shown and will report back. I noticed that the SKU field populated in your gif. Did you use the title as the SKU?

**Comment by blazemachine** [comment]
Yes, it is using name as SKU. He has done that in automatically mode.

**Comment by Rashidsalim** [comment]
I will see if I can do the same. Thank you
